name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:        # Allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository's source code
      - uses: actions/checkout@v2

      # Generate the Snake SVG and GIF
      - uses: Platane/snk@v3.2.0
        with:
          github_user_name: Nayeem-Ahmed1
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to the `output` branch using GitHub Pages Action
      - name: Push snake to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pa
